### PR TITLE
fix realm-join when using provisioning w/cloud-init

### PR DESCRIPTION
**Pull request by acortina-git**
fix  joining realm when provisioning rhel6 with cloud-init

### CODE REVIEW

**Comment by acortina-git** [comment]
tested this change on rhel6 and rhel7, only affects rhel6

**Comment by mmoll** [comment]
related: GH-361

**Comment by ekohl** [comment]
So the tricky thing here is that on RH systems it's convention to store the FQDN in the hostname while Debian prefers the shortname. I also thought that cloud-init sets the hostname and wonder in which cases these fixes are needed. Then again, I'm not that familiar with cloud-init.

**Comment by acortina-git** [comment]
Hi @ekohl 

mm then this could work:

```ruby
<% if @host.operatingsystem.family == 'Redhat' && @host.operatingsystem.major.to_i = 6 %>
hostname <%= @host %> 
<% else %>
hostname <%= @host.shortname %> 
<% end %>
```

**Comment by ekohl** [comment]
That could work yes though it should be `== 6`. Would you mind applying that? Please also rebase on current develop since that includes a fix for the tests.

**Comment by mmoll** [comment]
@alejojo what's the status here?

**Comment by mmoll** [comment]
rebased version: GH-633

**Pull request closed without merging**
