### PR TITLE
Fixes #10072: an 'admin' user with sudo rights is now being configured for cloud-init setups.

### PR DESCRIPTION
**Pull request by dmitri-d**
This allows for spcification of non-clear text password for root-like administrative account. Part of support for atomic vm provisioning.

### CODE REVIEW

**Comment by ekohl** [comment]
Trivial nitpick: typo in spcification in the commit message

**Comment by dmitri-d** [comment]
@ekohl: fixed.

**Comment by ekohl** [comment]
For reference, this replaces https://github.com/theforeman/community-templates/pull/185

I'm still not quite sure if everyone wants this by default. Maybe make passwordless sudo configurable and default to password sudo?

**Comment by dmitri-d** [comment]
Not sure re: configurable passwordless sudo -- it's pretty easy to change the template if someone decides they don't want authentication. Probably makes sense to ship a slightly more secure version of the template with authenticated sudo, unless there are objections?

**Comment by ekohl** [comment]
I think secure-by-default and have users modify the templates is fine.

**Comment by dmitri-d** [comment]
@ekohl: removed `NOPASSWD` from `admin` user sudo config.

**Comment by ekohl** [comment]
:+1:

**Comment by domcleal** [comment]
Thanks @witlessbird.

**Pull request merged**
