### PR TITLE
Syntax improvements for PXElinux templates - Use uppercase for keywords, and whitespace & indenting to make the code easier to read

### PR DESCRIPTION
**Pull request by stefanlasiewski**
Summary: Syntax improvements for PXElinux templates - Use uppercase for keywords, and whitespace & indenting to make the code easier to read.

Problem:

The PXElinux templates are difficult to read, especially when comparing
them against the documentation at http://www.syslinux.org/wiki/index.php/SYSLINUX
and while trying to read the ERB syntax at the same time.

Solution:

Make the PXElinux templates a little easier to read:
- Use uppercase letters for the syslinux keywords like KERNEL, APPEND, LABEL
- Use whitespace and indentation (4 spaces) to clarify where one section ends
  and the next begins.
- These changes follow the conventions already set forth in
  pxe/PXELinux_default.erb

There were no functional changes in this change. These are cosmetic
changes only.

### CODE REVIEW

**Comment by mmoll** [comment]
Please amend the commit message to have a short summary as first line, :+1: otherwise

**Comment by lzap** [comment]
Looks good, can you add vim/emacs expandtab special comments maybe? :-)

**Comment by ekohl** [comment]
I don't think we want special comments in the provisioning templates because they end up in the final configs, which I wouldn't want. Not sure about the rest.

About the PR itself, I agree with @mmoll that my only comment is on the commit message.

**Comment by stefanlasiewski** [comment]
Thanks. This is my first time submitting a pull request for this group.

Is my comment sufficient now, or would you like me to change it further?

**Comment by ekohl** [comment]
@stefanlasiewski we'd prefer you to amend the git commit for a good git history. The pull request description was clear enough. http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html is a good reference for writing commit messages. If you don't know how we can do it for you because git shouldn't hold back useful code improvements :)

**Comment by stefanlasiewski** [comment]
Oh I see. I think I can figure out how to amend the Git commit. And I need
the practice.

**Comment by stefanlasiewski** [comment]
Hi all,

I apologize, but it appears I did this merge in the wrong order.  Would it be possible for you to accept only 1ca99f2 ?

 mmol has advised me how to handle this in the future. Next time I'll try a topic branch.

**Comment by ekohl** [comment]
Done. Thanks for your contribution!

**Pull request closed without merging**
