### PR TITLE
enable/start puppet explicitly also on Debian 9

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
see https://anonscm.debian.org/cgit/pkg-puppet/puppet.git/plain/debian/NEWS

**Comment by mmoll** [comment]
@sathieu could you also have a look here?

**Comment by mmoll** [comment]
also, moving the enable/start part after the puppet run to get the cert signed.

**Comment by sathieu** [comment]
Great. Thanks.

**Pull request merged**
