### PR TITLE
Translate ssh package actions for debian

### PR DESCRIPTION
**Pull request by mdellweg**
apt does not have the concept of package groups (there are very dependency-heavy meta packages though). So this translates all Group actions to being plain actions. Also it should not hurt to run `apt-get update` every time.
Also i tried to translate the os_family question to which package manager is being used. This should help as soon as dnf enters the arena.

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
I like the os and package manager separation.

**Comment by mdellweg** [comment]
@ekohl any update on this one?

**Comment by mdellweg** [comment]
ping @ekohl, @mmoll, @lzap 
This is getting a little bit stale.

**Comment by ekohl** [comment]
Thanks! Apparently I had this still marked as TODO but that list is (too) long. Merged and I'll be happy to accept further PRs if there's a bug we missed :)

**Comment by mdellweg** [comment]
Thanks @ekohl !

**Pull request merged**
