### PR TITLE
Fixes #22139 - resolved atomic ostree conflict

### PR DESCRIPTION
**Pull request by lzap**
This resolves name clash, for more info see the issue.

### CODE REVIEW

**Review by dLobatog — COMMENTED** [review]
Sorry, ran into http://projects.theforeman.org/issues/23801 when testing this..

**Comment by lzap** [comment]
NP, thanks. You can still use non-CDN repositories. Let's just wait.

**Comment by mmoll** [comment]
what's the status here?

**Comment by lzap** [comment]
Ready for review.

**Comment by mmoll** [comment]
merged, díky @lzap!

**Pull request merged**
