### PR TITLE
Fixes #9287 - Configure networking during image provisioning

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by mmoll** [comment]
visually OK, I presume you tested it, I remember vaguely a discussion about network restart, but can't remember if that was for RH based OSes...

**Comment by ares** [comment]
yes, the test was also presented in cfgmgmt demo :-) we removed restarting of networking from kickstart template but here we must restart it, since the host is not rebooted after finish template is done

**Comment by ekohl** [comment]
I don't have a strong opinion about this. I don't like restarting the network during kickstart, but I see that it solves a problem so :+1:

**Comment by mmoll** [comment]
thanks @ares!

**Pull request merged**
