### PR TITLE
bootloader append

### PR DESCRIPTION
**Pull request by mikenowak**
The real reason for doing this is that quiet results in startup messages being hidden, which is not very useful for debugging purposes.

But it would also be useful to be able to add extra params.

### CODE REVIEW

**Comment by ekohl** [comment]
Looks good to me. Could you squash the commits?

**Comment by mikenowak** [comment]
@ekohl My apologies, this should be done now

**Comment by ekohl** [comment]
@mikenowak you now have 4 commits. I think http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html is a good read on how to get it back to 1. If you can't manage, we can do it for you when we merge it.

**Comment by mmoll** [comment]
it looks to me like the rebase did work, but the result was not force pushed.

**Comment by mikenowak** [comment]
@ekohl - thanks for the instructions - I think I've done this now.

**Comment by ekohl** [comment]
:+1:

**Comment by domcleal** [comment]
Merged as a5d76fb, thanks @mikenowak!

**Pull request closed without merging**
