### PR TITLE
Change the freeipa version check from le to lt

### PR DESCRIPTION
**Pull request by bmerjil**

### CODE REVIEW

**Comment by domcleal** [comment]
http://projects.theforeman.org/issues/10101 has more background on the change.  @stbenjam or @joshuabaird?

**Comment by stbenjam** [comment]
Oh, yes :+1: 4 doesn't need the sudo bits, the installer does it.

**Comment by domcleal** [comment]
Thanks @bmerjil!

**Comment by bmerjil** [comment]
No prob

**Comment by joshuabaird** [comment]
Thanks, @bmerjil!

On Apr 10, 2015, at 3:40 AM, bmerjil <notifications@github.com<mailto:notifications@github.com>> wrote:


No prob

**Pull request merged**
