### PR TITLE
coreos_cloudconfig missing end

### PR DESCRIPTION
**Pull request by dLobatog**
The latest commit introduced some conditions in this file without the
corresponding end.

### CODE REVIEW

**Comment by mikedevita** [comment]
this works for me fyi, it was missing the `<% end %>`

**Comment by mmoll** [comment]
I'm unsure if the end shouldn't go into line 28 instead of the else...

**Comment by dLobatog** [comment]
@mmoll You're right - otherwise if you set the update-strategy param the rendered snippet doesn't make much sense. Updated

**Comment by mmoll** [comment]
merged, gracias @dLobatog!

**Pull request merged**
