### PR TITLE
Change repo name for puppet 6. Fixes #27822

### PR DESCRIPTION
**Pull request by jacac**

### CODE REVIEW

**Comment by jacac** [comment]
@ekohl Is this the correct way?

**Comment by ekohl** [comment]
Slightly different. We use `Fixes #27822 - Change repo name for puppet 6`. That should allow our automation to pick it up.

**Comment by jacac** [comment]
I see that the the Foreman Bot picked up the pull. (https://projects.theforeman.org/issues/27822). Do you still want me to change the commit message?

**Comment by ekohl** [comment]
Looks like I forgot to submit my comment. Yes please because not all automation is so flexible and we always start with it which makes our git log consistent.

**Comment by sbschuermann** [comment]
Double Fix :)

**Comment by ekohl** [comment]
Replaced by https://github.com/theforeman/community-templates/pull/625

**Pull request closed without merging**
