### PR TITLE
Added comments about HTTP Boot workaround

### PR DESCRIPTION
**Pull request by lzap**
Just for better understanding in the future. Might remove it sometime.

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
These comments are always useful

**Comment by ekohl** [comment]
Looks like there is a merge conflict though. Mind resolving that?

**Comment by lzap** [comment]
Rebased, quick merge pls?

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
