### PR TITLE
Add enable-epel param

### PR DESCRIPTION
**Pull request by alexjfisher**
Defaults to true, but provides a way to disable the use of EPEL repos.

### CODE REVIEW

**Comment by mmoll** [comment]
:+1: from me, but could any EL user weigh in here? I think the original reason to have that was that Puppet needed packages from EPEL, which will not be required with Puppet 4 AIO packages.

**Comment by ekohl** [comment]
This wil still default to installing EPEL, right? If so :+1:

**Comment by alexjfisher** [comment]
@mmoll Correct, when installing from Puppetlabs PC1, EPEL isn't needed.  During testing, it was proving a bit unreliable too.  More than once, the provisioning hung after failing to install `epel-release`.  A dodgy mirror I guess?  If my servers need EPEL, I use puppet and a [rhn_channel](https://github.com/strider/puppet-rhnreg_ks/blob/master/lib/puppet/type/rhn_channel.rb) resource.

@ekohl Yes, the default behaviour shouldn't change.  I'm pretty sure I remember testing it too! ;)
`unless @host.param_false?` is used [here](https://github.com/theforeman/community-templates/blob/27c79c85de595204e626ecaf604eef17b34bc06d/snippets/freeipa_register.erb#L48) for the parameters that default to true.

**Comment by mmoll** [comment]
merged, thanks @alexjfisher!

**Pull request merged**
