### PR TITLE
Fixes #28896 Add template name to kickstart provision templates

### PR DESCRIPTION
**Pull request by stejskalleos**
**Description**
Display name of the kickstart template in the `/root/original-ks.cfg` file.

### CODE REVIEW

**Review by ares — CHANGES_REQUESTED** [review]
Looks sane, however it may be good to provide more context, e.g. `# This kickstart file was rendered from provisioning template "<%= @template_name %>"`

**Comment by stejskalleos** [comment]
Comment changed to `# This kickstart file was rendered from provisioning template "<%= @template_name %>".`

**Review by ezr-ondrej — APPROVED** [review]
If the goal is to have it only for kickstart templates, it looks good to me :)
Wouldn't it make sense to have it in more templates though?
Not necessarily in this PR :)

**Comment by ezr-ondrej** [comment]
@ares any more comments?

**Review by ares — COMMENTED** [review]
Just one tiny comment `from the Foreman provisioning template` would be better :-) I don't recall if debian stores preseed file somewhere and couldn't google ot quickly. @mmoll do you happen to know? If so, I'd say add it to preseed tempmate too, but not a blocker for this PR

**Comment by stejskalleos** [comment]
> Just one tiny comment from the Foreman provisioning template would be better :-)

Updated.

**Review by ares — APPROVED** [review]
no more comments, kickstart can be solved in a separate repo

edit: preseed of course

**Review by ezr-ondrej — APPROVED** [review]
Thanks @stejskalleos! :+1:

**Pull request merged**
