### PR TITLE
Fixes #17229 - add rex template to initiate SCAP scans

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Review by mmoll — APPROVED** [review]

**Comment by mmoll** [comment]
I have no idea of SCAP, but looks OK visually.

**Comment by ares** [comment]
@shlomizadok or @xprazak2 would you mind to test?

**Comment by shlomizadok** [comment]
Testing....

**Comment by shlomizadok** [comment]
Ack.
@ares++ works very nicely!

**Comment by mmoll** [comment]
merged, díky @ares!

**Pull request merged**
