### PR TITLE
Add disable-firewall paramater

### PR DESCRIPTION
**Pull request by brandonweeks**
Adding a firewall to optionally disable the firewall on EL based systems. Internally we are using an iptables based firewall configuration system and would prefer to have firewalld disabled on provisioning.

cc: @mmoll

### CODE REVIEW

**Comment by mmoll** [comment]
I'd rather like a parameter like `disable-firewall` to not change the defaults when not having the parameter. :+1: otherwise, I'm having something similar in my private templates.

**Comment by brandonweeks** [comment]
@mmoll done.

**Comment by mmoll** [comment]
:+1:

**Comment by mmoll** [comment]
oh, one thing, could this please also get added to the RHEL template?

**Comment by mmoll** [comment]
and, it's param_e_ter in the commit message ;)

**Comment by brandonweeks** [comment]
done and done.

**Comment by ekohl** [comment]
I'm generally not a fan of negative named variables but in this case I think having an enable-firewall parameter which defaults to true may be confusing as well. The code looks good so :+1: either way.

**Comment by mmoll** [comment]
merged, thanks @brandonweeks!

**Pull request merged**
