### PR TITLE
use correct provisioning URL for FreeBSD

### PR DESCRIPTION
**Pull request by mmoll**
found that after upgrading to 1.8, I wonder why it worked before :)

### CODE REVIEW

**Comment by ekohl** [comment]
I think it ```foreman_url``` changed in 1.8. Explicit over implicit anyway so :+1:

**Comment by domcleal** [comment]
How did it change, OOI?

**Comment by ekohl** [comment]
Maybe I only remember us talking about it, but I do recall us talking about the default argument for ```foreman_url``` because it's ambiguous what it exactly does.

**Comment by domcleal** [comment]
Yeah, true.  Often it refers to the "built" URL, so this change is good.  Thanks @mmoll!

**Pull request merged**
