### PR TITLE
Added missing finish options

### PR DESCRIPTION
**Pull request by lzap**
I think these guys were missing these options, this is untested but I was grepping our codebase for finish statements and these came up.

### CODE REVIEW

**Comment by ekohl** [comment]
Does the foreman show a deprecation for unspecified ```foreman_url```? Personally I think it should because it's ambiguous and I like this change.

**Comment by mmoll** [comment]
I think nobody uses these nowadays, but this is correct.

**Comment by mmoll** [comment]
merged, díky @lzap!

**Comment by lzap** [comment]
@ekohl we can even simply error out, deprecation warning first, yeah.

**Pull request merged**
