### PR TITLE
Fixes #27470 - Provide template for checking for package updates

### PR DESCRIPTION
**Pull request by adamruzicka**
community-templates counterpart of https://github.com/theforeman/foreman_remote_execution/pull/422

### CODE REVIEW

**Comment by ekohl** [comment]
Note the message is correct and you can't use Fixes here. That's because in Redmine it will end up only in one project and this way it won't actually close the issue.

**Comment by lzap** [comment]
I am doing review in the other PR.

**Comment by adamruzicka** [comment]
Moved the changes done in the REX PR here

**Review by lzap — APPROVED** [review]
It's a GO.

**Pull request merged**
