### PR TITLE
move remote_execution_ssh_keys to finish scripts

### PR DESCRIPTION
**Pull request by mmoll**
maybe I got something wrong, but I think this is a way better place ;)

### CODE REVIEW

**Comment by ekohl** [comment]
Maybe the same should be done for kickstart templates?

**Comment by mmoll** [comment]
it's already in the correct `%post` section, AFAICT

**Comment by ares** [comment]
looks right to me, we don't need it before finish script gets run and yes, kickstart already has it in %post

**Comment by stbenjam** [comment]
Also looks good to me, if this gets merged soon I can update my sync PR @ https://github.com/theforeman/foreman/pull/3167

**Comment by ekohl** [comment]
:+1:

**Comment by ekohl** [comment]
Thanks!

**Pull request closed without merging**
