### PR TITLE
OpenSUSE 13.2 has no yast2-runlevel anymore

### PR DESCRIPTION
**Pull request by mmoll**
...while it's needed on <13.2 for sshd to really get started on the installed system.

See https://groups.google.com/d/msg/foreman-users/ZfCoAdhJc5I/lMpmab1LTmEJ for a successful testing result. Maybe @mattiasgiese or @lazyfrosch also could have a look?

### CODE REVIEW

**Comment by mmoll** [comment]
or @lazyfrosch

**Comment by lazyfrosch** [comment]
Sorry, not using OpenSuSE anywhere currently...

**Comment by mmoll** [comment]
same here ;)

**Comment by mattiascockburn** [comment]
I have an internal test environment and am for the fact using openSUSE, but just for testing ;-)
I will try to test it this weekend and report back.

**Comment by mmoll** [comment]
now also including a few stylefixes

**Comment by ares** [comment]
@mmoll could you please reopen against develop branch? we renamed master to develop since we started branching this repo per foreman releases

**Pull request closed without merging**
