### PR TITLE
Fixes #25301 - support hosts without owner

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
this also fixes the other problem, if owner is hostgroup it does not respond to login, it's safer to use to_s which also works on nil

**Review by mbacovsky — APPROVED** [review]
Works fine, thanks @ares.

**Review by tbrisker — APPROVED** [review]
Thanks @ares !

**Comment by tbrisker** [comment]
:cherries: to 1.20 as e0dc734

**Comment by tbrisker** [comment]
and pulled into core as https://github.com/theforeman/foreman/commit/a25699d4e39778ab13ed681878ee8174975c03f6

**Comment by ares** [comment]
That was quick, thanks @mbacovsky and @tbrisker

**Pull request merged**
