### PR TITLE
Update remote_execution_ssh_keys.erb

### PR DESCRIPTION
**Pull request by markchristopherwest**
foreman threw an error: undefined method 'join' for...

Remove illegal call to .join

### CODE REVIEW

**Comment by ares** [comment]
I think this could still be array if someone uses smart variables instead of prameters. The question is if in your case, join was called on `nil` or on string. Both cases should be handled I think. Could you please add such detection? Something like

``` erb
<% keys = @host.params['remote_execution_ssh_keys'] %>
<% unless keys.nil? %>
  <% keys.respond_to?(:join) ? keys.join("\n") : keys %>
<% end %>
```

warning, untested and I'm not sure if `respond_to?` works in safemode

**Comment by mmoll** [comment]
I think there might be some confusion over `ssh_authorized_keys` vs. `remote_execution_ssh_keys`. @markchristopherwest when does that error occour? Are you having the remote_execution plugin installed and configured?

**Comment by stbenjam** [comment]
This parameter is actually set by the plugin, and it's an array.

**Comment by mmoll** [comment]
no reaction, closing.

**Pull request closed without merging**
