### PR TITLE
preseed: use linux/initrdefi for EFI

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
@sathieu @lzap could you have a look?

**Comment by sathieu** [comment]
@mmoll linuxefi doesn't work with Debian Kernel. I don't know why, probably because it's not signed.

I think that this should at least be configurable.

Side note: How can we get the boot type from the template?

**Comment by mmoll** [comment]
@sathieu interesting, somebody on IRC had a non-working configuration a few days ago, and that change fixed it. Does it wotk on EFI without the "efi" in the template for you? Is there a difference between Debian and Ubuntu regarding the signage?

**Comment by sathieu** [comment]
Debian jessie kernel is not signed. Debian stretch will (see https://lwn.net/Articles/703001/). Ubuntu is signed since 12.10 or so. I propose using this info as conditional. 

Also note that I've not tested Debian stretch on UEFI yet (I've only tested jessie).

**Comment by mmoll** [comment]
@sathieu I see... would something like the updated PR work?

**Comment by sathieu** [comment]
Looks good to me. Maybe rename efi_string to efi_suffix?

**Comment by mmoll** [comment]
good point, changed.

**Comment by lzap** [comment]
I am ok with the change, thanks.

**Pull request merged**
