### PR TITLE
Allow dynamic partition table for autoyast

### PR DESCRIPTION
**Pull request by Klaas-**
This change needs https://github.com/theforeman/foreman/pull/4076 to
work

How to use #Dynamic with autoyast:
the partition xml structure needs to be created by a shell script thats
run in inst-sys before the actual installation.
The general idea is you have /tmp/profile/autoinst.xml and after the
script is done you need to have a working autoyast file in
/tmp/profile/modified.xml

As an example:
you can echo your partiton table into a 3rd file (I usually use
/tmp/diskpart.cfg to keep in sync with my redhat installations) and sed
it into the autoinst.xml like this:
```
sed '/<\/ntp-client>/ r /tmp/diskpart.cfg' /tmp/profile/autoinst.xml > /tmp/profile/modified.xml
```

### CODE REVIEW

**Comment by Klaas-** [comment]
the foreman change is now merged, so this can be merged here :D its scheduled to be included in foreman 1.14

**Comment by mmoll** [comment]
@Klaas- I didn't test the actual dynamic feature, but trust you on that and didn't find any negative impacts on the standard setup.

**Comment by mmoll** [comment]
merged, danke @Klaas-!

**Comment by mmoll** [comment]
also cherry-picked for 1.14 as b0b0e49

**Comment by Klaas-** [comment]
thanks mmoll

**Pull request merged**
