### PR TITLE
Removed blacklist block for pxe_kernel_options

### PR DESCRIPTION
**Pull request by lzap**
This is now provided by Foreman core directly via pxe_kernel_options

### CODE REVIEW

**Comment by mmoll** [comment]
@lzap this needs a rebase :)

**Comment by lzap** [comment]
I have amended the last commit, thank you for review.

**Comment by mmoll** [comment]
merged, díky @lzap!

**Comment by lzap** [comment]
Tests are red, will take a look on Tuesday.

**Comment by mmoll** [comment]
that's GH-499

**Pull request merged**
