### PR TITLE
Add gpg key for puppet

### PR DESCRIPTION
**Pull request by hboetes**
Puppetlabs started signing packages, since the key was missing from the provisioning template the repo was rejected by the installed. This patch adds the key.

### CODE REVIEW

**Comment by mmoll** [comment]
please rebase onto the current develop branch and squash everything into one commit, then force-push 📍

**Comment by hboetes** [comment]
yes, this is getting messy

**Comment by hboetes** [comment]
ok, all fixed. Thanks @mmoll !

**Comment by mmoll** [comment]
I didn't test this, but it can't be more broken than before, so let's pull that in...

**Comment by mmoll** [comment]
merged, thanks @hboetes!

**Comment by hboetes** [comment]
I have no idea how it happened, but the key is wrong. :-(
It should be 7F438280EF8D349F and not 2ABFA143A0E46E11, which is the open suse key id.

**Pull request merged**
