### PR TITLE
Add "preseed-post-install-upgrade" option with default to none

### PR DESCRIPTION
**Pull request by derektamsen**
- Specify security upgrade options post installation. Choices are none, safe-upgrade, full-upgrade.
- Resolves GH-334

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
FYI we don't require a separate issue, just a PR is also fine.

**Comment by derektamsen** [comment]
Thanks! Sounds good. I have a couple more that I will just open PRs for.

**Comment by mmoll** [comment]
I'm fine with this, but wonder what the default of the installer is, because I think after a Foreman install of any Debian, I never needed updates, so maybe "none" is not the actual default (or maybe I was just lucky).

**Comment by derektamsen** [comment]
@mmoll I'm not really sure what the default of this is. I think their may also be a bug around the option but can't confirm. I was assuming the default was supposed to be `none` due to the documentation. I was having the opposite issue where I did not want the system to be upgraded and the option seemed to have no affect.

Based on my tests with the key I think the installation will always have the latest installed because if a security mirror is not specified it points to security.ubuntu.com (for ubuntu) via the debian-installer. Then, the installer selects the linux-image which will almost always be installed from the security repo.

From: https://help.ubuntu.com/lts/installation-guide/amd64/apbs04.html#preseed-pkgsel
```
# Whether to upgrade packages after debootstrap.
# Allowed values: none, safe-upgrade, full-upgrade
#d-i pkgsel/upgrade select none
```

**Comment by mmoll** [comment]
it for sure won't hurt, merged, thanks @derektamsen!

**Pull request merged**
