### PR TITLE
Refs #20271 - remove to_proc syntax

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Comment by lzap** [comment]
You need to poke @dLobatog to reimport templates for 1.15.x release.

**Comment by ares** [comment]
I was told this happens before every release, I sent a [PR](https://github.com/theforeman/foreman/pull/4591) in core against 1.15-stable but it was closed.

**Comment by mmoll** [comment]
The problem was not the syncing to core, but rather that the commit was not cherry-picked to 1.15-stable in the community-templates repo.

**Comment by ares** [comment]
Got it, thanks.

**Pull request merged**
