### PR TITLE
Explicitly set system name

### PR DESCRIPTION
**Pull request by lzap**
When Anaconda is unable to correctly set hostname, the default is `localhost.localdomain` which is not sufficient and usually errors out when such a content host exists or creates ducplicite entry.

This change explicitly sets system name via `--name` parameter which is I believe in rhsm for a long time.

### CODE REVIEW

**Comment by lzap** [comment]
Opinions @stbenjam ?

**Comment by stbenjam** [comment]
It looks fine, but note Katello doesn't actually use this snippet.  One of the old devs made it work with Katello and never finished the work to move Katello to actually using this snippet before he left.

(The Katello one uses --name already: https://github.com/Katello/katello/blob/master/app/views/foreman/unattended/snippets/_subscription_manager_registration.erb)

**Review by stbenjam — APPROVED** [review]

**Comment by lzap** [comment]
Oh it must be so confusing to ship two, shall we fix that?

By the way are you aware of a bug when hosts are being registered as "localhost"?

**Comment by stbenjam** [comment]
Yea, it needs fixing.  This snippet needs a lot of clean-up, I started it here just never got around to finishing it: https://github.com/theforeman/community-templates/pull/302.

Then Katello itself needs to support different parameter names, as this snippet doesn't use the same ones for activation keys, etc.

I'm not aware of anything off hand, Anaconda should be setting the host name before the snippet gets run AFAIK

**Pull request merged**
