### PR TITLE
Remove a redundant grep

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ares** [comment]
Good catch, works for me :+1:

**Comment by ekohl** [comment]
I tried to remove sed as well, but that didn't make it any better.

**Comment by mmoll** [comment]
@ekohl is that applyable to the preseed snippet as well?

**Comment by ekohl** [comment]
@mmoll it is so I've updated it.

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
