### PR TITLE
fixes #22857 - Remove RHEL default template

### PR DESCRIPTION
**Pull request by stbenjam**
The two templates work equally well on RHEL.  I don't believe there's a good reason to keep both around, as the kickstart default works fine on RHEL.

I'm working on getting rid of the templates in Katello too, so there's just one kickstart.  It'd reduce a lot of the problems where changes get introduced into kickstart default and don't get propagated to the RHEL version or the Katello version.

Hope this isn't too controversial :grin:

### CODE REVIEW

**Comment by lzap** [comment]
For the record, here is the diff:

```diff
$ diff provisioning_templates/provision/kickstart_default.erb provisioning_templates/provision/kickstart_rhel_default.erb
3c3
< name: Kickstart default
---
> name: Kickstart RHEL default
6,7c6
< - CentOS
< - Fedora
---
> - RedHat
26d24
< - disable-uek: boolean (default=false)
29d26
<   rhel_compatible = @host.operatingsystem.family == 'Redhat' && @host.operatingsystem.name != 'Fedora'
31c28
<   realm_compatible = (@host.operatingsystem.name == 'Fedora' && os_major >= 20) || (rhel_compatible && os_major >= 7)
---
>   realm_compatible = os_major >= 7 ? true : false
39c36
<   section_end = (rhel_compatible && os_major <= 5) ? '' : '%end'
---
>   section_end = os_major <= 5 ? '' : '%end'
64d60
< <% if rhel_compatible -%>
66d61
< <% end -%>
73,85d67
< <% if @host.operatingsystem.name == 'Fedora' -%>
< repo --name=fedora-everything --mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=fedora-<%= @host.operatingsystem.major %>&arch=<%= @host.architecture %><%= proxy_string %>
< <% end -%>
< 
< <% if @host.operatingsystem.name == 'OracleLinux' && os_major == 7 -%>
< repo --name="Server-Mysql"
< <% end -%>
< 
< <% if @host.operatingsystem.name == 'Fedora' and os_major <= 16 -%>
< # Bootloader exception for Fedora 16:
< bootloader --append="<%= host_param('bootloader-append') || 'nofb quiet splash=quiet' %> <%=ks_console%>" <%= grub_pass %>
< part biosboot --fstype=biosboot --size=1
< <% else -%>
90d71
< <% end -%>
99,101d79
< <% if @host.respond_to?(:bootdisk_build?) && @host.bootdisk_build? %>
< reboot --eject
< <% else -%>
103d80
< <% end -%>
156c133
< <% if rhel_compatible && !host_param_false?('enable-epel') -%>
---
> <% unless host_param_false?('enable-epel') -%>
159a137,138
> <%= snippet 'redhat_register' %>
> 
190,195d168
< <% if @host.operatingsystem.name == 'OracleLinux' && host_param_true?('disable-uek') -%>
< # Uninstall the Oracle Unbreakable Kernel packages
< yum -t -y remove kernel-uek*
< sed -e 's/DEFAULTKERNEL=kernel-uek/DEFAULTKERNEL=kernel/g' -i /etc/sysconfig/kernel
< <% end -%>
< 
196a170
> 
```

**Comment by lzap** [comment]
I don't think this is controversial at all, RHEL template only had as we can see this line:

    <%= snippet 'redhat_register' %>

Do you want to add it into the default template? I think it would be reasonable to put it there under some condition, for example if OS name is "RHEL" or "Red Hat Enterprise Linux" or if explicitly told by parameter, so users can decide when to include this. Maybe you have a better way in mind.

As we can see, RHEL template was already a bit off (some params missing), so it's good to have a consistent template.

**Review by lzap — APPROVED** [review]
WFM but want to hear more opinions on that. Thanks for working on this, this was confusing.

**Comment by stbenjam** [comment]
Oh right, I meant to add that to the CentOS template. redhat_register snippet supports subscription-manager, so it's relevant for CentOS and Fedora when they are attached to Katello.  

The next step for me is to finish https://github.com/theforeman/community-templates/pull/302 which reconciles redhat_register with Katello's snippet.  Once that's done I can get rid of the templates in Katello's repo too.

**Comment by mmoll** [comment]
merged, thanks @stbenjam!

**Pull request merged**
