### PR TITLE
Fix 'medium_uri' in suse-template

### PR DESCRIPTION
**Pull request by m-bucher**
autoyast_default_ipxe did not work (needs to be cherry-picked to 1.20)
I have not tested it on 1.19, yet

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
Could you make sure the file is not executable? You're changing the mode from 0644 to 0755 now.

**Comment by m-bucher** [comment]
@ekohl thanks, just fixed the file-mode

**Review by ShimShtein — CHANGES_REQUESTED** [review]
I think it was a bug in the core that was fixed by https://github.com/theforeman/foreman/pull/6316.

Can you please recheck with newer foreman release?
If it works, we can ask for a backport into 1.20 too.

**Comment by m-bucher** [comment]
@ShimShtein, you are right when I add your change from theforeman/foreman#6316 to my foreman-1.20 it works.

I'd much appreciate the fix to be backported to 1.20

**Comment by ShimShtein** [comment]
@m-bucher, done: https://github.com/theforeman/foreman/pull/6316#issuecomment-452302120

**Pull request closed without merging**
