### PR TITLE
Use os_family instead of os_name to verify if it's a Suse based OS

### PR DESCRIPTION
**Pull request by sbernhard**
In case enable-puppetlabs-X-repo is set we need to adjust the path.

### CODE REVIEW

**Review by ekohl — APPROVED** [review]

**Comment by mmoll** [comment]
AIO packages are only available for SLES, the change was made intentionally back then.

**Comment by sbernhard** [comment]
Good your point. Do you think, that the SLES packages would work on OpenSUSE, too?

**Comment by mmoll** [comment]
Maybe. But even if that's the case I wouldn't want to pull this into the canonical upstream templates.

**Comment by mmoll** [comment]
Closing for now, if there are OpenSUSE AIO RPMs or guarantees about binary compatibilties between SLES and OpenSUSE, this can get reworked.

**Pull request closed without merging**
