### PR TITLE
Add ipa4 support to freeipa sudo snippet

### PR DESCRIPTION
**Pull request by joshuabaird**

### CODE REVIEW

**Comment by mmoll** [comment]
@stbenjam could you review?

**Comment by stbenjam** [comment]
Yay! Thanks @joshuabaird! I'll try this out ASAP.

**Comment by stbenjam** [comment]
@mmoll Looks good to me, tried on FreeIPA 4 with IPAv3 and IPAv4 clients and sudo works on both as expected :tada: !

**Comment by mmoll** [comment]
merged, thanks @joshuabaird and @stbenjam! :shaved_ice:

**Pull request closed without merging**
