### PR TITLE
use .present?

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by ares** [comment]
looks good to me, I think there's a rule that we keep templates compatible for 2 releases so once 1.12 is out, I think this can be merged

**Comment by domcleal** [comment]
> I think there's a rule that we keep templates compatible for 2 releases

Not since the repo branch layout's [changed](https://groups.google.com/d/msg/foreman-dev/7do3i4ONFnY/J3_iTJRq56gJ) - now develop only needs to be compatible with Foreman's develop.

**Comment by domcleal** [comment]
Merged, thanks @mmoll - also cherry picked with 8f1c3b1c to 1.12-stable.

**Comment by ares** [comment]
right, thanks

**Pull request merged**
