### PR TITLE
Implement param_true/false? methods on host struct to fix tests

### PR DESCRIPTION
**Pull request by domcleal**
Fixes GH-215

Sorry about breaking tests when merging, I completely overlooked it.

### CODE REVIEW

**Comment by mmoll** [comment]
could you add `sudo: false` to .travis.yml also? :)

**Comment by domcleal** [comment]
Running, should fix that deprecation warning.

**Comment by mmoll** [comment]
adding

``` yaml
addons:
  apt:
    packages:
    - python-urlgrabber
```

should fix the new error.

**Comment by domcleal** [comment]
More occurred as it then installs pykickstart using sudo into the root directory.  I'll have a look at that separately in my own time :)

**Comment by mmoll** [comment]
merged, thanks @domcleal!

**Pull request merged**
