### PR TITLE
Suppport interfaces with ipv6 but no ipv4 address

### PR DESCRIPTION
**Pull request by jovandeginste**
This change allows interfaces to have only an ipv6 address, while ipv4
is either blank (no v4 support on that interface) or dhcp.

### CODE REVIEW

**Comment by mmoll** [comment]
I didn't test this, but it's looking correct. @ares? @timogoebel?

**Review by timogoebel — APPROVED** [review]
LGTM.

**Comment by ares** [comment]
looks good, but shouldn't the same be applied for bonds?

I'd like to get the [refactoring PR](https://github.com/theforeman/community-templates/pull/348) merged first since that deduplicates this but if that won't happen anytime soon, I don't insist on waiting :-)

**Comment by jovandeginste** [comment]
I added code for the bonds -- I also moved ipv6 out of the dhcp part here ...

**Comment by mmoll** [comment]
merged, bedankt @jovandeginste!

**Pull request merged**
