### PR TITLE
refactor and extend kickstart finish scripts

### PR DESCRIPTION
**Pull request by mmoll**
This unifies all kickstart finish scripts as much as possible, using the same variables and replicating behaviour. Tested with CentOS 6 & 7 Cloud-Images.

### CODE REVIEW

**Comment by jkroepke** [comment]
Its still required to splitt centos and rhel?

**Comment by ekohl** [comment]
At first glance it looks good.

**Comment by stbenjam** [comment]
> Its still required to splitt centos and rhel?

I don't think it's necessary anymore, I'm not really sure what the history was and why they were split, but there should be no difference provisioning say CentOS 7 vs. RHEL, except maybe registering to the CDN, but even then that can be controlled already by parameters.

**Comment by stbenjam** [comment]
And looking at the diff, there doesn't seem to be a whole lot of difference.

**Comment by ekohl** [comment]
```provision.erb``` used to use %packages where ```provision_rhel.erb``` used post scripts. We've converged more to post scripts.

**Comment by mmoll** [comment]
I'm tackling another part of this in my next planned PR, in which I want to move the whole Puppet and EPEL stuff out of provisioning into postinst for all OSes.

**Comment by mmoll** [comment]
anything else needed to get this in? ☝️

**Review by ekohl — APPROVED** [review]
I didn't test this, but the code looks good.

**Comment by mmoll** [comment]
what's the status here?

**Comment by timogoebel** [comment]
I'm planing on testing this, hopefully this week. If they are not objections I'll merge.

**Review by timogoebel — APPROVED** [review]
LGTM, thanks @mmoll.

**Pull request merged**
