### PR TITLE
Add the parameter DOMAIN (if it is specified)

### PR DESCRIPTION
**Pull request by jovandeginste**
This helps NetworkManager to configure the `search` inside
`/etc/resolv.conf`.

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
I think this is correct. @lzap?

**Comment by mmoll** [comment]
according to the docs I could find, this looks correct

**Comment by mmoll** [comment]
merged, bedankt @jovandeginste!

**Comment by lzap** [comment]
Vacations, sorry. Yup looks good to me.

**Pull request merged**
