### PR TITLE
Only set old keymap on Debian Squeeze or older installs

### PR DESCRIPTION
**Pull request by derektamsen**
- only set `console-keymaps-at/keymap seen true` in `preseed/provision.erb` when Debian OS Version is <= Squeeze (6.0).
- Resolves GH-330

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
Makes sense to me. @mmoll?

**Comment by mmoll** [comment]
While I didn't run into the error, according to the linkd Debian issue, this is looking correct.

**Comment by mmoll** [comment]
merged, thanks @derektamsen!

**Comment by derektamsen** [comment]
Great thanks! I found the errors when working on the travis tests :smile:

**Pull request merged**
