### PR TITLE
Fixes #28782 - complete compare ch report template

### PR DESCRIPTION
**Pull request by waldirio**
The complete code with all changes made before. At this time, using the correct branch also issue on redmine.

### CODE REVIEW

**Review by lzap — APPROVED** [review]
Thanks.

**Comment by ares** [comment]
@lzap, this was I believe not ready, see the comment in https://github.com/theforeman/community-templates/pull/670#issuecomment-574812971, I think @waldirio opened this but forgot to link the old PR.

So we need to get https://github.com/theforeman/foreman/pull/7361/files in, the `version` macro does not exist yet in core. Also this template may change based on the comments in this PR.

**Comment by lzap** [comment]
I am going to get the template fixed, sorry about that!

**Comment by lzap** [comment]
I have rewritten this from scratch, but this is flawed - this cannot be done at the moment. We don't have RPM versioning scheme implementation in Ruby yet.

**Pull request merged**
