### PR TITLE
move EPEL and Puppet repos/install fully into snippets

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
This is yet untested, @ares @domcleal @ekohl let me know, what you think.
Also, some conditionals for EL4 based OSes are removed, RHEL4 will be EOLed in six weeks.

**Comment by ekohl** [comment]
Personally I prefer ```%repo``` and ```%package``` over snippets because you get a better progress indicator while installing and it feels cleaner. Sadly that doesn't work with RHEL due to registration and such so this may be cleaner and unified.

**Comment by mmoll** [comment]
of course this does not work with SUSE... However, I'll split out some smaller parts first and come back here in a few days.

**Comment by ares** [comment]
I agree with @ekohl, I think the unification and deduplication justifies the change.

**Comment by mmoll** [comment]
this is ready to be reviewed now.

**Pull request merged**
