### PR TITLE
Generic Windows Templates

### PR DESCRIPTION
**Pull request by UXabre**
`These set of templates are tested on Windows Server 2012/R2, Server 2016 and Server 2019.`

**Highly Customizable**
The installation script is injected into the image a boot, so it's highly customizable (instead of having to rebuild your images for each change).

**Build for remoting**
It also automatically configures winRM based on your configuration settings (but I must admit, it only touches the most basic of use-cases) ==> I already have OpenSSH running on windows server 2016 which seems a much, much, much better fit for remote communication! But that will be updated in a latter phase.

**Hot patching**
While I was on it, I also added the possibility to hot-patch the system, meaning you can included needed updates at installation time as well (if you don't have a rigid ISO building set-up on your hands, this will probably be a welcome addition).

**Themable**
Finally I've included some themability of windows (but it's entirely optional!)

**Fast**
I've tried my best to parallelize as many steps as possible to give the, probable, fastest installation times.
I does require HTTP support from the PXE (hence the addition of iPXE as this provides a HTTP method).

**Important**
Needs https://github.com/theforeman/foreman/pull/7131 before merging.

### CODE REVIEW

**Comment by canihavethisone** [comment]
Can I suggest you also add a GPT EFI Partition Table.  Here is what I have been using:

<%#
name: Windows GPT EFI
snippet: false
model: Ptable
os_family: Windows
%>
:: Disk Partitioning Layout

set DPFILE=%SYSTEMDRIVE%\dp.txt

:: Append commands to Diskpart file
echo select disk 0 > %DPFILE%
echo clean >> %DPFILE%
echo convert gpt >> %DPFILE%
echo create partition EFI size=100 >> %DPFILE%
echo select partition 1 >> %DPFILE%
echo format quick fs=fat32 label="System" >> %DPFILE%
echo set id="c12a7328-f81f-11d2-ba4b-00a0c93ec93b" >> %DPFILE%
echo assign letter="K" >> %DPFILE%
echo create partition msr size=128 >> %DPFILE%
echo create partition primary >> %DPFILE%
echo select partition 3 >> %DPFILE%
echo shrink minimum=450 >> %DPFILE%
echo format quick fs=ntfs label="<%= @host.operatingsystem.family -%>" >> %DPFILE%
echo select partition 3 >> %DPFILE%
echo assign letter="C" >> %DPFILE%
echo create partition primary >> %DPFILE%
echo format quick fs=ntfs label="WinRE" >> %DPFILE%
echo set id="de94bba4-06d1-4d40-a16a-bfd50179d6ac" >> %DPFILE%
echo gpt attributes=0x8000000000000001 >> %DPFILE%
echo exit >> %DPFILE%

:: Execute Diskpart with file as script argument
diskpart /s %DPFILE%

:: Remove Diskpart script file
del %DPFILE%

**Comment by UXabre** [comment]
Hi @canihavethisone , will add this! Great addition!

**Comment by canihavethisone** [comment]
No problem.  I also have a custom iPXE template for Windows build that uses bootx64.efi etc placed in an adjacent directory on the build mirror.  Note the quirky requirement to list the filename twice.  This find was the result of googling and testing.  Feel free do play around and include it if you so wish:

    #!ipxe
    <%#
    name: Windows iPXE
    snippet: false
    model: ProvisioningTemplate
    kind: iPXE
    oses:
    - windows
    %>
    ifopen
    cpuid --ext 29 && set arch amd64 || set arch x86

    <% keyboard_params = 'console-setup/ask_detect=false console-setup/layout=USA console-setup/variant=USA keyboard-configuration/layoutcode=us' -%>
    <% static = @host.token.nil? ? '?static=yes' : '&static=yes' -%>

    kernel <%= @host.os.medium_uri(@host) %>/../win-efi///wimboot
    initrd <%= @host.os.medium_uri(@host) %>/../win-efi///bootx64.efi bootx64.efi
    initrd <%= @host.os.medium_uri(@host) %>/../win-efi///bcd bcd
    initrd <%= @host.os.medium_uri(@host) %>/../win-efi///boot.sdi boot.sdi
    initrd <%= @host.os.medium_uri(@host) %>/../win-efi///boot.wim boot.wim

    boot

It will be awesome to see full Windows support in Foreman at last.

BTW, I have used these to provision Win10.  My other templates are similar to yours and were originally sourced from the wimaging project at https://github.com/AutomationD/foreman-wimaging/tree/1bd8f0facff80c19a5eccc12c01e8febd00f701e/wimaging.  I look forward to testing your modifications over the next few weeks.

Thanks also for looking into the password issue - it has been bugging me for ages and reported intermittently by others.  The appending of 'AdministratorPassword' is straight forward but the password length bug appears to be the issue now.

**Review by lzap — APPROVED** [review]
I am good, any objections @mmoll ?

I'd appreciate a blogpost or post into our Tutorial section on Discourse with instructions. Or even better a PR into https://github.com/theforeman/foreman-documentation/tree/master/guides/doc-Provisioning_Guide so this would be forever in our next-generation docs.

**Comment by UXabre** [comment]
You're reading my mind @lzap, I thought just the same. Although heavily inspired by the wimaging work done many moons ago, I'm 100% pro writing a fresh update on the subject as the scripting part is done slightly different; also, I hope to perhaps improve the scripts a teeny tiny bit :-)

I'll get to work!

**Comment by mmoll** [comment]
merged, thnks @UXabre!

**Comment by UXabre** [comment]
@canihavethisone I think it's probably best to also include your additional changes as a new PR? Would love to see support for UEFI based systems.

**Comment by lzap** [comment]
We already had a template named "provisioning_templates/PXELinux/waik_default_pxelinux.erb" but I am not sure how relevant it is. Can you research how useful this Windows template is and maybe drop it in another PR?

**Comment by lzap** [comment]
Also created https://projects.theforeman.org/issues/28153 task once we sync templates

**Pull request merged**
