### PR TITLE
Fixes #24360 - add support for provisioning on vlan

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ekohl** [comment]
Could you have a look at the test failure? I think we need to mock `vlanid` in our tests.

**Comment by lzap** [comment]
Any chance of updating Debian too?

I think this line needs to be broken apart soon into array so we can add elements into array in an arbitrary Ruby block - would be much cleaner. We do this in PXELinux templates.

**Comment by timogoebel** [comment]
This requires the host to have a trunked network port. I don't think it's a good idea to rely solely on the interfaces vlanid parameter here.

We define the vlanid on the subnet to have a chance to match it with the corresponding vmware network. But the hosts aren't trunked.

**Comment by lzap** [comment]
Can you elaborate your concern Timo? We have multiple customers asking for this, they specifically want to use trunk VLAN on provisioning interface, including PXE and discovery. For this reason I am working on https://github.com/theforeman/foreman/pull/5989

**Comment by timogoebel** [comment]
@lzap: I'd love the feature being added. To hopefully clarify my concern: Not every host that is installed in a subnet that has the vlan id parameter set actually had a trunked interface. I fear we need a parameter "trunked: yes/no" on the nic model.

**Comment by lzap** [comment]
Agreed, this patch is reading vlanid from host tho.

@ares in order to support this in PXE environment, we also need to add this to PXE templates: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/installation_guide/chap-anaconda-boot-options

**Comment by timogoebel** [comment]
> Agreed, this patch is reading vlanid from host tho.

True, but that is basically delegated to the subnet. ;-)

**Comment by lzap** [comment]
> True, but that is basically delegated to the subnet. ;-)

Whoops.

**Comment by mmoll** [comment]
@ares what's the status here?

**Comment by lzap** [comment]
I've implemented this already, closing.

**Comment by lzap** [comment]
@timogoebel about your concern - I don't understand why would you set VLANID on a NIC for a network that is what I call "native VLAN" (VLAN done by switch). If that's only for informative (inventory) purposes, then it could be a use case, then simply do not fill "attached_to" and it will not be used in the template.

**Comment by ares** [comment]
@lzap it would be good to know, which commit implemented it. Please update https://projects.theforeman.org/issues/24360 with the link to the PR so it (and BZ) gets updated.

**Pull request closed without merging**
