### PR TITLE
Kickstart: Install lsb package by default, it is required for core facts

### PR DESCRIPTION
**Pull request by sathieu**

### CODE REVIEW

**Comment by domcleal** [comment]
Fine by me, :+1:

**Comment by ekohl** [comment]
I always hated redhat-lsb because of the many dependencies, but this doesn't appear to have any. Is redhat-core-lsb available on all platforms and why was I not aware of this in the past?

**Comment by domcleal** [comment]
It was added circa RHEL 6.3 precisely for this reason.  It has *some* dependencies, but certainly none of the LSB printing group, etc.

**Comment by ekohl** [comment]
I don't have EL5 at hand, but does it also work there?

**Comment by domcleal** [comment]
No, it won't - so it should be wrapped in `if os_major >= 6` (it should be fine on Fedora).

**Comment by sathieu** [comment]
Thanks for your remarks. I've updated the PR.

**Comment by mmoll** [comment]
I have a modification like this in my local templates for a long time, so :+1:.

On Debian/Ubuntu ```lsb-release``` could be added and It's also needed for some grains when using SaltStack.

**Comment by sathieu** [comment]
@mmoll lsb-base is already in Debian preseed:
```
d-i pkgsel/include string <%= puppet_package %> <%= salt_package %> lsb-release
```
Ref: https://github.com/theforeman/community-templates/blob/master/preseed/provision.erb#L130

**Comment by mmoll** [comment]
Indeed, sorry.
Merging, thanks @sathieu

**Pull request merged**
