### PR TITLE
Fixes #22742 - Add link delay option to kickstart

### PR DESCRIPTION
**Pull request by jcpunk**
This PR adds use of the link delay options included in https://github.com/theforeman/foreman/pull/6035

### CODE REVIEW

**Comment by jcpunk** [comment]
Just checking in

**Comment by mmoll** [comment]
@jcpunk could you rebase? :)

**Comment by jcpunk** [comment]
done :)

**Comment by mmoll** [comment]
merged, thanks @jcpunk!

**Pull request merged**
