### PR TITLE
Use kernel-detected mac addresses instead of current configuration

### PR DESCRIPTION
**Pull request by jovandeginste**
We scan the mac addresses of interfaces according to the kernel,
instead of relying on what's currently configured.

This might solve issues if you use bonding during installation
(when your two ethernet adapters have the same mac address). The
order here is to first seek bonding slaves, and then consider all
other devices.

### CODE REVIEW

**Comment by lzap** [comment]
Can you add `2>/dev/null` to the grep command, because on some platforms you can hit:

```
# grep -l xxxxxxxxxx /sys/class/net/*/{bonding_slave/perm_hwaddr,address} | awk -F '/' '// {print $5}' | head -1
grep: /sys/class/net/*/bonding_slave/perm_hwaddr: No such file or directory
enp30s0
```

**Comment by jovandeginste** [comment]
@lzap Something like this?

**Review by lzap — APPROVED** [review]
Something like this, @ares any objections?

**Comment by ares** [comment]
No objections, I haven't tested it but looks good to me.

**Comment by lzap** [comment]
Thanks a lot.

**Pull request merged**
