### PR TITLE
drop support for EL4 based OSes

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
According to https://access.redhat.com/support/policy/updates/errata RHEL 4 reaches "End of Extended Life-cycle Support" on March 31, 2017

**Review by ekohl — APPROVED** [review]

**Comment by lzap** [comment]
I think this is incorrect, we should really change `os_major > 4` to `os_major > 5` because now we changed the behavior of the templates a lot. @mmoll ?

**Comment by mmoll** [comment]
5, 6 and 7 are >4, so this would always be true? (edit, 5 is of course not >5)

**Comment by lzap** [comment]
Yeah I get it, sure.

**Pull request merged**
