### PR TITLE
Use proxy on FreeBSD if specified

### PR DESCRIPTION
**Pull request by sathieu**

### CODE REVIEW

**Comment by ekohl** [comment]
:+1:

**Comment by mmoll** [comment]
Please add --direct to the fetches that go the foreman instance, as that's in line with the other OSes (using proxy only for the repositories). Also, it should be tested if the behaviour is like desired in the chroot (finish script), as the pkg commands also would need the proxy to be set then.

**Comment by sathieu** [comment]
I've not finished testing FreeBSD yet. Please wait a bit before merging.

**Comment by mmoll** [comment]
It would also be nice if @mmatuska could provide a 10.1 image over at http://mfsbsd.vx.sk/files/foreman/

**Comment by sathieu** [comment]
I've now finished the tests and the FreeBSD is running well

**Comment by mmoll** [comment]
Works very well and finally forced me to tweak my apt-cacher-ng config for FreeBSD pkgng, merci @sathieu!

**Pull request merged**
