### PR TITLE
Allow puppetlabs repo base URL to be modified

### PR DESCRIPTION
**Pull request by treydock**
This would be useful for sites that prefer to use local mirrors.

### CODE REVIEW

**Comment by mmoll** [comment]
I think this doesn't work for quite some situations, e.g. when having something like http://my.mirr.or/pupeptlabs/apt and http://my.mirr.or/puppetlabs/yum. See GH-267 for more discussion on that topic.

**Comment by treydock** [comment]
Should work, my local mirror is https://fqdn/puppetlabs and so that'd be value of puppetlabs-repo-base.  That discussion looks to suggest more parameters isn't always better which makes sense.

**Comment by mmoll** [comment]
@treydock Well, my mirror is not organzied in that way... ;)

I'm not opposed to adding more parameters, it's not nice, but the result of the fact that we don't have complex data structures available to set for the templates.

**Comment by tbrisker** [comment]
This PR has been inactive for a long time now, closing. Feel free to reopen it if it is still relevant. thanks @treydock !

**Pull request closed without merging**
