### PR TITLE
Added kickstart custom

### PR DESCRIPTION
**Pull request by lzap**
We don't ship a good kickstart example how to partition EFI and BIOS systems. This supports both. Untested.

### CODE REVIEW

**Comment by pjayKHV** [comment]
I think its best to also change 

> part /boot **--fstype="ext4"** --ondisk=<%= dev %> --size=1024

 to 

> part /boot **--fstype="<%= fstype %>"** --ondisk=<%= dev %> --size=1024

 so it would also default to xfs instead of ext4.

**Review by pjayKHV — CHANGES_REQUESTED** [review]
I think its best to also change

part /boot --fstype="ext4" --ondisk=<%= dev %> --size=1024

to

part /boot --fstype="<%= fstype %>" --ondisk=<%= dev %> --size=1024

so it would also default to xfs instead of ext4.

**Comment by lzap** [comment]
Oh yeah, I haven't noticed that on RHEL7 onwards /boot is xfs, but older RHELs still expect this to be ext2-compatible and won't boot. Let me change it and do this only when this is RHEL7+.

**Comment by lzap** [comment]
Updated, if you can test this version that would be *very* appreciated. I haven't tested myself.

**Comment by mmoll** [comment]
@pjayKHV could you have a look? :eyes:

**Comment by pjayKHV** [comment]
> @pjayKHV could you have a look?

I will test it, as soon as i get foreman up and running... Had to kill all of the deployments that i had at the moment... Sorry...

**Comment by pjayKHV** [comment]
Tested the template with Foreman 1.23.1 and CentOS 7.7... Everything seems to be good... Sorry for the delay...

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
